steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_FULL_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_FULL_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - '$REPO_FULL_NAME'
    - '--image=gcr.io/$PROJECT_ID/$REPO_FULL_NAME:$COMMIT_SHA'
    - '--platform=managed'
    - '--allow-unauthenticated'